z <- c(0,0.25,0.5,0.75,1)

print("Lambda = 0")
summary(qpois(z,lambda = 0))
print("Lambda = 1")
summary(qpois(z,lambda = 1))
print("Lambda = 2")
summary(qpois(z,lambda = 2))
print("Lambda = 3")
summary(qpois(z,lambda = 3))
print("Lambda = 5.2")
summary(qpois(z,lambda = 5.2))
print("Lambda = 10.8")
summary(qpois(z,lambda = 10.8))

par(mfrow=c(3,2))
colors = palette.colors(6)

plot(x, ppois(x, 0), main = paste("Funzione di distribuzione di Poisson con lambda =",0), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[1])
abline(h=z, col="purple", lty = 2)
plot(x, ppois(x, 1), main = paste("Funzione di distribuzione di Poisson con lambda =",1), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[2])
abline(h=z, col="purple", lty = 2)
plot(x, ppois(x, 2), main = paste("Funzione di distribuzione di Poisson con lambda =",2), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[3])
abline(h=z, col="purple", lty = 2)
plot(x, ppois(x, 3), main = paste("Funzione di distribuzione di Poisson con lambda =",3), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[4])
abline(h=z, col="purple", lty = 2)
plot(x, ppois(x, 5.2), main = paste("Funzione di distribuzione di Poisson con lambda =",5), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[5])
abline(h=z, col="purple", lty = 2)
plot(x, ppois(x, 10.8), main = paste("Funzione di distribuzione di Poisson con lambda =",10), xlab="x",ylab=expression(P(X<=x)), ylim=c(0,1) ,type ="s", col = colors[6])
abline(h=z, col="purple", lty = 2)
